### PR TITLE
Remove executable permission from file(s).

### PR DESCRIPTION
**Pull request by eldiener**

### CODE REVIEW

**Comment by pfultz2** [comment]
This file should be executable. Why does it need to be removed?

**Comment by eldiener** [comment]
The file is not removed. Why should it be executable in the first place ?

**Comment by pfultz2** [comment]
> Why should it be executable in the first place ?

Because I execute it to generate the readme from the other documentation. Why should it not be executable?

**Comment by eldiener** [comment]
Normally executable files are not committed to Boost git repositories. I realize that there are exceptions. I will bring up this general issue on the mailing list. If you want to you can close this PR.

**Pull request closed without merging**
